version: "3"

# the port used in ports must match the port specified in env
# changes to environment variables will take precendent over the server.cfg and must be defined
# a description of the environemnt variables is in the README.md and server.cfg

services:
  necesse-server:
    container_name: necesse_server
    image: karyeet/necesse-server-docker:latest
    stdin_open: true
    tty: true
    ports:
      - 14159:14159/udp
    volumes:
      - ./server.cfg:/root/.config/Necesse/cfg/server.cfg
      - ./banned.cfg:/root/.config/Necesse/cfg/banned.cfg
      - ./saves:/root/.config/Necesse/saves
      - ./logs:/root/.config/Necesse/logs
      - ./mods:/root/.config/Necesse/mods
    environment:
      - world=myNewWorld
      - port=14159
      - slots=10 
      - password=
      - maxClientLatencySeconds=30
      - pauseWhenEmpty=true
      - giveClientsPower=true
      - logging=true
      - language=en
      - unloadLevelsCooldown=30
      - worldBorderSize=-1
      - droppedItemsLifeMinutes=0
      - unloadSettlements = false
      - maxSettlementsPerPlayer = -1
      - maxSettlersPerSettlement = -1
      - jobSearchRange=100
      - zipSaves=true
      - MOTD=